AWSTemplateFormatVersion: "2010-09-09"
Description: create an s3 pucket that has public read and the name is passed as parameter
Parameters:
  BucketName:
    Default: shalabi-public-s3
    Type: String
    Description: Bucket name.

Resources:
  DummyServer:
    Type: "AWS::S3::Bucket"
    Properties:
    # documentation can be found https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
      BucketName: !Ref BucketName
      AccessControl: PublicRead

